INSERT INTO curso
(curso_descricao, curso_ementa)
VALUES
('Photoshop5', 'Dicas de Photoshop CC'),
('PHP', 'Curso de PHP para iniciantes'),
('Java', 'Introdução à Linguagem Java'),
('MySQL', 'Bancos de Dados MySQL'),
('Word', 'Curso completo de Word'),
('Python', 'Curso de Python'),
('POO', 'Curso de Programação Orientada a Objetos'),
('Excel', 'Curso completo de Excel'),
('Responsividade', 'Curso de Responsividade'),
('C++', 'Curso de C++ com Orientação a Objetos'),
('C#', 'Curso de C#'),
('Android', 'Curso de Desenvolvimento de Aplicativos para Android'),
('JavaScript', 'Curso de JavaScript'),
('PowerPoint', 'Curso completo de PowerPoint'),
('Swift', 'Curso de Desenvolvimento de Aplicativos para iOS'),
('Hardware', 'Curso de Montagem e Manutenção de PCs'),
('Redes', 'Curso de Redes para Iniciantes'),
('Segurança', 'Curso de Segurança'),
('SEO', 'Curso de Otimização de Sites'),
('Premiere', 'Curso de Edição de Vídeos com Premiere'),
('After Effects', 'Curso de Efeitos em Vídeos com After Effects'),
('WordPress', 'Curso de Criação de Sites com WordPress'),
('Joomla', 'Curso de Criação de Sites com Joomla'),
('Magento', 'Curso de Criação de Lojas Virtuais com Magento'),
('Modelagem de Dados', 'Curso de Modelagem de Dados'),
('HTML4', 'Curso Básico de HTML versão 4.0'),
('PHP7', 'Curso de PHP versão 7.0'),
('PHP4', 'Curso de PHP versão 4.0');

INSERT INTO aluno
(aluno_nome)
VALUES
('Kelley'),
('Armstrong'),
('Carr'),
('Murray'),
('Ellis'),
('Phillips'),
('Williamson'),
('Harris'),
('James'),
('Jacobs'),
('Black'),
('Schmidt'),
('Webb'),
('Jacobs'),
('Medina'),
('Morgan'),
('Nguyen'),
('Day'),
('Bryant'),
('Alexander'),
('Chapman'),
('Kelly'),
('Stephens'),
('Porter'),
('Owens'),
('Scott'),
('Price'),
('Weaver'),
('Willis'),
('Torres'),
('Smith'),
('Bradley'),
('Cruz'),
('Williamson'),
('Kennedy'),
('Hawkins'),
('Allen'),
('Watkins'),
('Ferguson'),
('Nguyen'),
('Lawrence'),
('Oliver'),
('Johnson'),
('Crawford'),
('Armstrong'),
('Dixon'),
('Snyder'),
('Coleman'),
('Reed'),
('Ross'),
('Watkins'),
('Allen'),
('Baker'),
('Garcia'),
('Lane'),
('Watson'),
('Boyd'),
('Young'),
('Cooper'),
('Jordan');